language: go
install:
  - go get github.com/spf13/hugo
before_script:
  - git clone https://github.com/lapsivesinokkaelainlaakari/hugo-base16-theme themes/base16
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
script:
  - ./build-and-deploy.sh
